### ISSUE TITLE
market currency

### ISSUE THREAD

**Issue by OsculaUltima** [josh-greenlaw/bedrock-portal#20]
Is it possible to make a market currency that isnt just diamonds? Diamonds, while a source of value, are rare enough that buying cheaper items isnt feasible, except in excessive bulk or being overpriced. And for newer players, it discourages market buying because they need diamonds. I'd like to suggest either using a different material like emeralds, having a conversion rate between the two, or making an entirely new material as currency. If possible also somehow tying it in with the website currency would be ideal imo.

**Comment by josh-greenlaw** [comment]
Thanks for the suggestion, but in game server economies aren't tied to the portal site, per se. Any in game item can be configured as purchased with portal currency by admins, but it doesn't actually work the other way (the Bedrock hosting software is very limited in what feedback you can get). If this changes in the future, deeper integrations will be added.
